[package]
name = "adventoffrog"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1"
arrayvec = "0.7"
clap = { version = "4.4.10", features = ["derive"] }

[dev-dependencies]
indoc = "2"
